name: serialport_flutter
description: Serial Port plugin for Android devices
version: 0.0.1
homepage: https://saeedqasemi.ir
repository: https://github.com/sgsm74/serialport_flutter

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.serialport_flutter
        pluginClass: SerialportFlutterPlugin